name: QuickSeeds
main: us.hinchy.QuickSeeds.QuickSeedsPlugin
version: 0.3.0
description: Plant seeds quicker. More time to tend to your animals.
commands:
  qsreload:
    description: Reload the QuickSeeds config.
    permission: quickseeds.reload
    usage: "/qsreload"